version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: